---

- apt: name={{ item }} state=latest
  with_items:
        - nginx 

- name: Copy config 
  synchronize: src={{ role_path }}/files/{{ item }} dest=/etc/nginx/
  notify: reload nginx
  with_items:
        - "sites-enabled"
        - "snippets"
        - "nginx.conf"

