---

- name: create network
  docker_network:
    name: syte2_net

- name: mongo container
  docker_container:
    name: mongo 
    image: mongo:3.4.0
    state: started
    restart_policy: always
    volumes:
      - /data/lib/mongo:/data/db
    networks:
      - syte2_net

- name: syte2 container
  docker_container:
    name: syte2
    image: docker.galayko.rocks/syte2
    state: started
    restart_policy: always
    networks:
      - syte2_net
    ports:
       - "3000:3000"
