pipeline:
        deploy-agent:
                image: docker:stable
                commands:
                        - docker build ./containers/agent -t docker.galayko.rocks/drone-agent
                        - docker push docker.galayko.rocks/drone-agent
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
        deploy:
                image: docker.galayko.rocks/drone-agent 
                commands:
                        - make all
                volumes: 
                        - /home/ubuntu/.ssh:/root/.ssh

