---

- name: drone server 
  docker_container:
    name: drone-server
    image: drone/drone:0.7
    state: started
    network_mode: host
    restart_policy: False 
    volumes:
     - "/var/lib/drone:/var/lib/drone/"
    env:
     DRONE_OPEN: true
     DRONE_ADMIN: ngalayko
     DRONE_HOST: "{{ lookup('env','DRONE_HOST') }}"
     DRONE_SECRET: "{{ lookup('env', 'DRONE_SECRET') }}"
     DRONE_GITHUB: true
     DRONE_GITHUB_CLIENT: "{{ lookup('env', 'DRONE_GITHUB_CLIENT') }}"
     DRONE_GITHUB_SECRET: "{{ lookup('env', 'DRONE_GITHUB_SECRET') }}" 
