---

- file: path=/data/lib/docker state=directory mode=0755
- file: src=/data/lib/docker dest=/var/lib/docker state=link

- apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present
- apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present update_cache=yes

- apt: name={{ item }} state=latest
  with_items:
    - docker-engine
    - python-pip

- pip: name="docker-py==1.9.0"

- service: name=docker enabled=yes state=started
