# docker run -d -p 5000:5000 --name registry registry:2
- name: docker-registry container
  docker_container:
    name: docker-registry
    image: registry:2.5
    state: started
    network_mode: host
    restart_policy: always
    volumes:
      - /data/lib/docker-registry:/var/lib/registry
