---

- apt: name={{ item }} state=latest
  with_items:
        - nginx

- apt_repository: repo=ppa:certbot/certbot

- apt: name={{ item }} state=latest
  with_items:
        - python-certbot-nginx 

- name: copy config
  synchronize: src={{ role_path }}/files/{{ item }} dest=/etc/nginx/
  with_items:
        - "sites-enabled"

- name: run certbot
  shell: certbot -n --agree-tos --nginx -m ngalayko@gmail.com -d {{ item }}
  become: yes
  ignore_errors: yes 
  with_items:
          - "docker.galayko.rocks"
          - "galayko.rocks"
          - "drone.galayko.rocks"

- name: run openssl
  shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  become: yes

- name: Creates daily certs update 
  cron: minute="20" hour="5" weekday="*"
        name="Update Let's Encrypt certs"
        user="root"
        job="/usr/bin/certbot renew --quiet"

- name: delete default
  shell: rm /etc/nginx/sites-enabled/default
  notify: reload nginx
